# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run: git submodule update --init --recursive

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run build!
      - run:
          name: build
          command: |
            mkdir -p ./public/shuho
            yarn build --deploy ./public/shuho
          when: always

      - store_artifacts:
          path: ./public/

      # deploy
      - deployment:
          deploy:
            branch: master
            commands:
              - mkdocs build --clean
              - git config --global user.email 38fanjia+github@gmail.com
              - git config --global user.name 38fanjia
              - cp ./public/shuho/* ./build/shuho
              - git add --all ./public/shuho
              - git commit -m "add shuho"
              - git pull git@github.com:38fanjia/38fanjia.github.io.git master
              - git push git@github.com:38fanjia/38fanjia.github.io.git master:shuho
