on:
  pull_request:
    types: [opened, synchronize]

name: Lint and Deploy (Staging)

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: "[INFO] Versions"
      run: |
        echo "node: `node --version`"
        echo "npm:  v`npm --version`"
        echo "yarn: v`yarn --version`"

    - name: package install
      run: yarn install

    - name: lint and type check
      run: |
        yarn lint
        yarn stylelint
        yarn type-check
      env:
        CI: true

  build_and_deploy:
    name: build and staging deploy
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: "[INFO] Versions"
      run: |
        echo "node: `node --version`"
        echo "npm:  v`npm --version`"
        echo "yarn: v`yarn --version`"

    - name: package install
      run: yarn install

    - name: build
      run: yarn build
